# Generated by Django 4.2.6 on 2023-11-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_attend_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField()),
                ('class_notes', models.TextField()),
                ('date', models.DateField()),
                ('sched_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customadmin.class')),
            ],
        ),
    ]
