# Generated by Django 4.2.6 on 2023-11-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customadmin", "0008_expense_alter_membership_membership_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["date_paid", "expense"]},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["user"]},
        ),
        migrations.RemoveField(
            model_name="membership",
            name="membership_paid",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.AddField(
            model_name="membership",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="customadmin.membership",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="waiver_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="waiver_signed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
